### ISSUE TITLE
Is there a way to easily cache, or pre-generate the "popular" content filter?

### ISSUE THREAD

**Issue by codepotato** [jrc9designstudio/statamic-google-analytics-v2#10]
First off, thank you ever so much for the development of this plugin, my client loves it! 

However, we're running into issues where a widget displaying the popular posts (based on the google_analytics filter) is causing a delay in loading the page by around 15 seconds. Is there an easy way to pre-generate the popular content and cache it?

**Comment by codepotato** [comment]
Any ideas on this?

**Comment by jcohlmeyer** [comment]
My first thought here would be to make sure you have caching turned on on the website. [Static caching](https://docs.statamic.com/caching#static-page) is awesome if you can get it working for your site. 

In addition you could try editing the cache time settings so that the page views are cached for longer.
<img width="1685" alt="Screen Shot 2019-07-22 at 3 40 03 PM" src="https://user-images.githubusercontent.com/1778271/61660058-08d92b00-ac97-11e9-8201-6246fb9d11ea.png">

Finally, I may suggest using the `{{ cache }}` tag to cache a template fragment as described here: https://docs.statamic.com/caching#template-fragments

Please let me know if any of these solutions work for you and thanks for the feedback.

**Comment by jcohlmeyer** [comment]
@codepotato I added a cache to the `{{ google_analytics:hits }}` tag and set it to a default of 1 day [here](https://github.com/jrc9designstudio/statamic-google-analytics-v2/commit/804d400389d51cabf2f7f07b3dab0d9ce6342391), hopefully, this will help speed up the results. I have a few other ideas but they make take a bit more work, or be a different addon that allows for providing a key to the `{{ cache }}` tag to allow cross-page caching.

Cache warming is outside of the scope of this addon but could be a nice addon of its own.

I will include this update in the next release but please do let me know if any of this helps your situation.

**Comment by codepotato** [comment]
That's amazing, thanks @jcohlmeyer. 

I agree, cache pre-warming would be ace as that'll solve the issue. 

I did originally use the {cache} tags but found that for the user who landed on the site when the cache needed rebuilding it would take AGES to load the page. Hopefully this'll solve it!

**Comment by jcohlmeyer** [comment]
@codepotato were you able to test this fix? If so was it able to fix the issue for you or do you still see long loading times?
