### ISSUE TITLE
Allow Translations

### ISSUE THREAD

**Issue by luizboaretto** [jrc9designstudio/statamic-google-analytics-v2#11]
Please allow this addon to be translated. Not just the settings.

**Comment by jcohlmeyer** [comment]
@luizboaretto I have gone through the addon and made all strings I could find translatable here: https://github.com/jrc9designstudio/statamic-google-analytics-v2/commit/655c9791a13d744c937296b317b63c13b1b70044

Please let me know if this works for you or if you see anything I missed.

Unfortunately, it is not possible to translated fields within a grid field within the settings page because of a limitation of Statamic.

If you have translation files you would be willing to send me I would be happy to include them in the addon.

These changes will be included in the next release but I would love your feedback beforehand.

Thanks,
Jonathan

**Comment by luizboaretto** [comment]
@jcohlmeyer Thanks for the speed solving this! 😍 

Only problem I found was under "Settings", see:
![Google_Analytics_Configurações___Statamic](https://user-images.githubusercontent.com/32047234/61731888-cd039b80-ad52-11e9-9ef8-23c5d0a6b64d.png)

[Lang for pt_BR](https://www.dropbox.com/s/tjaouqe989jpsns/statamic_google_analytics_addon_pt.zip?dl=0)

**Comment by jcohlmeyer** [comment]
@luizboaretto thanks for sending over the translation. I looked into it and it does not look like these section headings are currently translatable, another Statamic limitation.

I have submitted a feature request on the v2-hub [here](https://github.com/statamic/v2-hub/issues/2422). If you can give this a 👍 and leave a comment / expand upon what I have written this will help a lot.

**Comment by luizboaretto** [comment]
@jcohlmeyer Typo... Can you change the lang folder to **br** ?

It's a [Portuguese Brazilian](https://en.wikipedia.org/wiki/ISO_3166-2:BR). Not Portugal. Sorry for that.
