### ISSUE TITLE
Improve Date Range Picker

### ISSUE THREAD

**Issue by zoeply** [jrc9designstudio/statamic-google-analytics-v2#4]
The date picker appears to be broken. I try to select a date range but as soon as I click out of the field it goes back to the default dd/mm/yyyy. This is in chrome, then in Safari there isn't anything in those fields at all (not even the default date placeholders).

![chrome](https://user-images.githubusercontent.com/38232710/45604997-f2fa4880-ba7c-11e8-9c0d-9bb7fd571085.png)
![safari](https://user-images.githubusercontent.com/38232710/45604998-f392df00-ba7c-11e8-8b9f-41eefb95470c.png)

(tested in both Chrome and Safari) - see screenshots

**Comment by jcohlmeyer** [comment]
@zoeply I can not replicate the date field is a native browser date field. I have not been able to replicate your issue unless you are not selecting the date in the date picker? You need to click on the date you want. The date 'highlighted' is not picked unless you click on it.

This is how the native date picker in Chrome works.

Safari as of now does not support the date field (https://caniuse.com/#feat=input-datetime).

I have plans to improve the date picker. I will let you know when these improvements land.

**Comment by zoeply** [comment]
Hey @jcohlmeyer I've taken a quick loom video to show you what I'm experiencing: https://www.useloom.com/share/998b8b4be4e240b5b2e3c459cf40f027 

I can open the date picker window, and click on a date and I can also type in a date, but when I click away from the field it goes back to the default dd/mm/yyyy. This happens for both start and end date, so there's no way for me to see any data because it won't let me set a time window

Have you updated this to work with the latest chrome?

**Comment by jcohlmeyer** [comment]
Hey @zoeply have you completed the reporting setup in the [docs](https://statamic.com/marketplace/addons/google-analytics/docs#reporting-setup).

It looks like there is no data being received. Data should show up even before you use the date filters.

I think the date filters may not be working because of an error with the setup.

I should really improve this error message though. Please advise if following the guide above helps resolve your issue.
